dist: bionic

language: python

services:
  - memcached

matrix:
  include:
    - python: 3.8
      env: TOXENV=py3
    - python: 3.8
      env: TOXENV=py3-cython
    - python: pypy3
      env: TOXENV=pypy3

install:
    - pip install tox

script:
    - tox
